service: tokenizacionTarjeta

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal
  stage: dev
  region: us-west-2
  environment: 
    DB_MYSQL_TYPE: mysql
    DB_MYSQL_HOST: localhost
    DB_MYSQL_PORT: 3306
    DB_MYSQL_USER: root
    DB_MYSQL_PASSWORD: holamundo2020
    DB_MYSQL_NAME: culqui
    DB_MONGO_HOST: localhost
    DB_MONGO_PORT: 27017
    DB_MONGO_NAME: culqui
    URL_API_COMMERCE: http://localhost:3000/dev/commerce
    SECRET_KEY: sk_test_4b9c5b9c5b9c5b9c5b9c5b9c
functions:
  create-token-card:
    handler: src/infra/controller/card.createTokenCard
    description: Lambda function
    memorySize: 256
    events:
      - http:
          path: /card
          method: post
          cors: true
  get-card-by-tokken:
    handler: src/infra/controller/card.getCardByTokken
    description: Lambda function
    memorySize: 256
    events:
      - http:
          path: /card/tokken
          method: post
          cors: true          
  get-commerce-by-pk:
    handler: src/infra/controller/commerce.validateCommerceByPK
    description: Lambda function
    memorySize: 256
    events:
      - http:
          path: /commerce
          method: post
          cors: true          
